import React, { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';

function Dashboard() {
    const [clubsData, setClubsData] = useState([]);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState(null);
    const [searchTag, setSearchTag] = useState('');

    useEffect(() => {
        const fetchClubs = async () => {
            setLoading(true);
            setError(null);
            try {
                // Fetch from static JSON file generated by GitHub Actions
                const response = await fetch('/mon-dashboard-brawl/clubs-data.json');
                if (!response.ok) {
                    throw new Error('Failed to load club data');
                }
                const data = await response.json();
                setClubsData(data);
            } catch (err) {
                setError("Failed to load club data: " + err.message);
            } finally {
                setLoading(false);
            }
        };

        fetchClubs();
    }, []);

    const handleSearch = (e) => {
        e.preventDefault();
        if (searchTag) {
            const cleanTag = searchTag.replace('#', '');
            window.location.href = `/mon-dashboard-brawl/club/${cleanTag}`;
        }
    };

    if (loading) return <div className="loading" style={{ color: 'white', marginTop: '50px' }}>Loading Club Data...</div>;
    if (error) return <div className="error">{error}</div>;

    // Get last update time from first club
    const lastUpdate = clubsData[0]?.fetchedAt ? new Date(clubsData[0].fetchedAt).toLocaleString('fr-FR') : 'Unknown';

    return (
        <div>
            <h2 className="card-title" style={{ fontSize: '2rem', textAlign: 'center' }}>Club Dashboard</h2>
            <p style={{ textAlign: 'center', color: 'var(--bs-text-muted)', marginBottom: '1rem' }}>
                Dernière mise à jour : {lastUpdate}
            </p>

            <div className="mb-4 text-center">
                <form onSubmit={handleSearch} style={{ display: 'inline-block' }}>
                    <input
                        type="text"
                        placeholder="Search Club by Tag (e.g. 29UPLG8QQ)"
                        className="api-input"
                        style={{ width: '300px', marginRight: '10px' }}
                        value={searchTag}
                        onChange={(e) => setSearchTag(e.target.value)}
                    />
                    <button type="submit" className="btn-back" style={{ background: 'var(--bs-blue)', color: 'white', border: 'none' }}>
                        Search
                    </button>
                </form>
            </div>

            <div className="card-grid">
                {clubsData.map((club, index) => (
                    <Link to={`/club/${club.tag.replace('#', '')}`} key={index} style={{ display: 'block' }}>
                        <div className="card">
                            <h3 className="card-title">{club.name || club.configName}</h3>
                            {club.error ? (
                                <div style={{ color: '#ff6b6b' }}>
                                    Error loading data: {club.errorMessage}
                                </div>
                            ) : (
                                <>
                                    <div className="stat-row">
                                        <span className="stat-label">Total Trophies</span>
                                        <span className="stat-value" style={{ color: 'var(--bs-yellow)' }}>
                                            {club.trophies?.toLocaleString()}
                                        </span>
                                    </div>
                                    <div className="stat-row">
                                        <span className="stat-label">Members</span>
                                        <span className="stat-value">{club.members?.length} / 30</span>
                                    </div>
                                    <div className="stat-row">
                                        <span className="stat-label">Required Trophies</span>
                                        <span className="stat-value">{club.requiredTrophies?.toLocaleString()}</span>
                                    </div>
                                    <div className="stat-row" style={{ marginTop: '1rem', borderTop: '1px solid rgba(255,255,255,0.1)', paddingTop: '0.5rem' }}>
                                        <span className="stat-label">Top Player</span>
                                    </div>
                                    <div style={{ fontWeight: 'bold', color: 'var(--bs-blue)' }}>
                                        {club.members?.sort((a, b) => b.trophies - a.trophies)[0]?.name || 'N/A'}
                                    </div>
                                </>
                            )}
                        </div>
                    </Link>
                ))}
            </div>
        </div>
    );
}

export default Dashboard;
